### ISSUE TITLE
two new disposable addresses

### ISSUE THREAD

**Issue by mipapo** [nojacko/email-data-disposable#2]
spamfence.net
inboxcleant.com

(Sorry no time to add these)

**Comment by mipapo** [comment]
men.piquate.com is not a disposable address, but a spamming address (contact forms and registrations). What should I do with that one?

**Comment by nojacko** [comment]
Try https://www.stopforumspam.com/

You'll need to raise a pull request for those two domains above. I don't have time to do it myself.

**Comment by mipapo** [comment]
@nojacko  I already had an eye on stopforumspam, but I'm not that satisfied with them ;) Thanks for your reply

**Comment by nojacko** [comment]
Can't win them all. recaptcha might help.
